server:
  port: 8100
  tomcat:
    connection-timeout: 180000
  netty:
    connection-timeout: 180000
  jetty:
    connection-idle-timeout: 180000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 55MB
  mvc:
    servlet:
      load-on-startup: 1
  application:
    name: Namosun_graduate_project
  redis:
    port: 6380
    password: "@java2springboot"
    host: 47.111.13.56
  datasource:
    druid:
      initial-size: 1
    url: jdbc:mysql://47.111.13.56:3307/namosun_graduate_project?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "@java2springboot"
  main:
    allow-bean-definition-overriding: true

  freemarker:
    charset: UTF-8
    expose-session-attributes: true
    content-type: text/html;charset=UTF-8
    suffix: .html
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/static/,classpath:/static/,classpath:/public


Namosun.graduate.file.save-path: /namosun
Namosun.graduate.program-path: /namosun/Program.exe
Namosun.graduate.out-path: /namosun/output
Namosun.graduate.isLinux: true